### ISSUE TITLE
ExplodedAssembly workbench does not work in FreeCAD 0.18

### ISSUE THREAD

**Issue by dcapeletti** [JMG1/ExplodedAssembly#13]
See https://forum.freecadweb.org/viewtopic.php?f=3&t=36400
I installed the bank from addons manager. 

OS: Debian GNU/Linux 9 (stretch)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.18.16110 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 0.18.1)
Hash: f7dccfaa909e5b9da26bf50c4a22ccca9bb10c40
Python version: 3.6.7
Qt version: 5.6.2
Coin version: 4.0.0a
OCC version: 7.3.0
Locale: Spanish/Argentina (es_AR)

Error:

```
Exploded Assembly workbench loaded
Running the Python command 'PlayForward' failed:
Traceback (most recent call last):
  File "/home/dcapeletti/.FreeCAD/Mod/ExplodedAssembly/EAInit.py", line 221, in Activated
    ea.runAnimation()
  File "/home/dcapeletti/.FreeCAD/Mod/ExplodedAssembly/ExplodedAssembly.py", line 337, in runAnimation
    traj_iterator = xrange(number_of_trajectories)

name 'xrange' is not defined
```

The file to test is this https://github.com/JMG1/ExplodedAssembly/blob/master/example.fcstd

**Comment by easyw** [comment]
@dcapeletti 
there is already a PR for this issue... 
[PR 12](https://github.com/JMG1/ExplodedAssembly/pull/12)

**Comment by dcapeletti** [comment]
Well, thank you. I close the issue.
