### ISSUE TITLE
Failure to Load example

### ISSUE THREAD

**Issue by morgajel** [JMG1/ExplodedAssembly#2]
I've just started playing with freecad and tried to use this to get a better view of what I'm working on, however loading the example causes it to crash.

```
App::DocumentObjectGroupPython: No property found with name ExpressionEngine and type App::PropertyExpressionEngine
*** Abort *** an exception was raised, but no catch was found.
        ... The exception is:SIGSEGV 'segmentation violation' detected. Address 51

```

This is using the latest mint freecad (0.15  Revision: 4671 git)

**Comment by JMG1** [comment]
Please, update your FreeCAD version:

sudo add-apt-repository ppa:freecad-maintainers/freecad-stable

sudo apt-get update

sudo apt-get upgrade
