### ISSUE TITLE
exploded can not apply for assembly4

### ISSUE THREAD

**Issue by BurningTeng** [JMG1/ExplodedAssembly#30]
[bug_exploded.zip](https://github.com/JMG1/ExplodedAssembly/files/11934871/bug_exploded.zip)
FreeCAD version 0.20

(1) Select one face
(2)Select another face
(3)Then following error occurs:
 <Part> ViewProviderExt.cpp(1267): Cannot compute Inventor representation for the shape of _1#trajectory_line001: Bnd_Box is void

**Comment by JMG1** [comment]
Exploded assembly is not compatible with the assembly workbenches.
