### ISSUE TITLE
Color change of part

### ISSUE THREAD

**Issue by mmaukii** [JMG1/ExplodedAssembly#8]
Hello!

I have a transpartent red part in my freecad file. If i put an animation to it and start the animation it brings up the recompute sign in the tree view and changes it color it transparency. Can send you an example file if you would like.

Greets and thanks for this awesome tool

Update: Problem connected to other error. Nothing to do with workbench!!

**Comment by JMG1** [comment]
Hi!
Nice that its solved. BTW, next release will have a functionality to modify the transparency of parts in animation, but is not working yet.
