### ISSUE TITLE
Updating ExplodedAssembly WB to be compatible with the upcoming 0.18 release (req. py3 and Qt5 compatibility)

### ISSUE THREAD

**Issue by luzpaz** [JMG1/ExplodedAssembly#9]
Ref: https://github.com/FreeCAD/FreeCAD-addons/issues/93

**Comment by luzpaz** [comment]
@JMG1 please follow-up. thanks!

**Comment by luzpaz** [comment]
@JMG1 any news?

**Comment by JMG1** [comment]
Seems that with the 562c05f  is working now for python3 and FreeCAD 18.

**Comment by luzpaz** [comment]
Nice. Closing this issue then.
